export const URLs = {
  BASE: "/",
  SINGLE_ORDER: "/single-order",
  PAYMENT: "/payment",
  BULK_ORDER: "/bulk-order",
  HOW_IT_WORKS: "/how-it-works",
  CONTACT: "/contact",
  LOGIN: "/login",
  SIGN_UP: "/signup",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  ORDER_INVOICE: "/order-invoice",
  TERMS_AND_CONDITIONS: "/terms-and-conditions",
  PRIVACY_POLICY: "/privacy-and-policy",
  DASHBOARD: "/dashboard",
  PRICING: "/pricing",
  ORDER_CONFIRMATION: "/order-confirmation",
  SAMPLE: "/sample",
};
